name: React-app heroku-deploy

on :
  push:
    branches:
      - preprod
  pull_request:
    branches:
      - preprod

jobs:
  build:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm install  # npm ci

      - name: Run Linter
        run: eslint . --ext .js,.jsx,.ts,.tsx

      - name: Run the tests
        run: npm test -- --coverage

      - name: Deploy to Heroku
        uses: akhileshns/heroku-deploy@v3.5.7
        with:
          heroku_api_key: ${{secrets.HEROKU_KEY}}
          heroku_app_name: ${{secrets.HEROKU_APP_PREPROD}}
          heroku_email: ${{secrets.HEROKU_EMAIL}}
